apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-internal-gateway
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.mg.com"   # Domain name of the external website