{{- range $service:= .Values.services}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$service}}-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: ./chart
    repoURL: "https://github.com/mohamedgomaa23722/argo-service.git"
    targetRevision: master
    helm:
      parameters:
        - name: "service"
          value: {{$service}}
      values: |-
         {{- printf "service/%s.yaml" $service | $.Files.Get | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
{{- end}}